[features]
seeds = false
skip-lint = false
[programs.localnet]
amm_test = "5iJ1KCrWEQpR4FDMJrQWMdLFv3HdBF45kpzabkghmBPx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/mars/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
