[features]
seeds = false
skip-lint = false
[programs.localnet]
vega_core = "6jMXqfgZoguXohoWktL9UBhAqADYJSZYMC47ENoY2DvW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/deankang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
